name: Greetings

on: [pull_request_target]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            👋 Hello @${{ github.actor }}, thank you for submitting a 🚀 PR! To allow your work to be integrated as seamlessly as possible, we advise you to:
            - [ ] Verify your PR is **up-to-date with origin/main.
            - [ ] Verify your code met all the requirements mentioned in our [Coding guidelines](https://ulcampus-my.sharepoint.com/:w:/g/personal/darian_reyesfernandezdebulnes_ul_ie/ETwawQ8qBzJGsZ7PkhSinAwBeF_pqllmCxCknkDTauAxQw?e=CVJyxg).
            - [ ] Verify all Workflow Actions **checks are passing**.
